cask_args appdir: "/Applications"

brew "mas"

cask "ghostty"
cask "font-hack-nerd-font"
cask "raycast"
cask "libreoffice"

# Media preview dependencies
brew "poppler"    # PDF to image conversion (pdftoppm)
brew "ffmpeg"     # Video thumbnail generation
