cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "mas"

cask "alacritty"
cask "deepl"
cask "docker"
cask "font-hack-nerd-font"
cask "microsoft-excel"
cask "microsoft-word"
cask "microsost-powerpoint"
cask "raycast"
cask "visual-studio-code"
cask "zoom"

mas "RunCat", id: 1429033973

